<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" />
        <PackageReference Include="Asp.Versioning.OpenApi" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
      <ProjectReference Include="..\Onboarding.Domain\Onboarding.Domain.csproj" />
      <ProjectReference Include="..\Onboarding.Application\Onboarding.Application.csproj" />
      <ProjectReference Include="..\Onboarding.Infrastructure\Onboarding.Infrastructure.csproj" />
      <ProjectReference Include="..\Verification.Contracts\Verification.Contracts.csproj" />
      <ProjectReference Include="..\Accounts.Contracts\Accounts.Contracts.csproj" />
    </ItemGroup>

</Project>
