// <auto-generated />
using System;
using Atlas.Onboarding.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atlas.Onboarding.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OnboardingDbContext))]
    partial class OnboardingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Onboarding.Domain.Applications.OnboardingApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlockingIdentity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasComputedColumnSql("CONCAT([Market], '|', [IdentifierType], '|', [IdentifierIssuingCountry], '|', [IdentifierValue])", true);

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BlockingIdentity")
                        .IsUnique()
                        .HasDatabaseName("UX_Applications_BlockingIdentity")
                        .HasFilter("[Status] <> 'Rejected'");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Applications_IdempotencyKey");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("Atlas.Onboarding.Domain.Applications.OnboardingApplication", b =>
                {
                    b.OwnsOne("Atlas.Onboarding.Domain.Applications.Applicant", "Applicant", b1 =>
                        {
                            b1.Property<Guid>("OnboardingApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date")
                                .HasColumnName("DateOfBirth");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("Email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("Nationality");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("varchar(16)")
                                .HasColumnName("Phone");

                            b1.HasKey("OnboardingApplicationId");

                            b1.ToTable("Applications");

                            b1.WithOwner()
                                .HasForeignKey("OnboardingApplicationId");
                        });

                    b.OwnsOne("Atlas.Onboarding.Domain.Applications.ApplicantIdentifier", "Identifier", b1 =>
                        {
                            b1.Property<Guid>("OnboardingApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IssuingCountry")
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("IdentifierIssuingCountry");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("IdentifierType");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .IsUnicode(false)
                                .HasColumnType("varchar(13)")
                                .HasColumnName("IdentifierValue");

                            b1.HasKey("OnboardingApplicationId");

                            b1.ToTable("Applications");

                            b1.WithOwner()
                                .HasForeignKey("OnboardingApplicationId");
                        });

                    b.Navigation("Applicant")
                        .IsRequired();

                    b.Navigation("Identifier")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
