<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Onboarding.Domain\Onboarding.Domain.csproj" />
      <ProjectReference Include="..\Onboarding.Application\Onboarding.Application.csproj" />
      <ProjectReference Include="..\BuildingBlocks\Persistence\Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Azure.Storage.Blobs" />
      <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
